[templates."REDMI K90"]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "2510DRK44C"
device = "annibale"
product = "annibale"
fingerprint = ""
name = "annibale"
marketname = "REDMI K90"
author = "Github@orangesroof"