[templates."REDMI Turbo 4 Pro "]
manufacturer = "Xiaomi"
brand = "Redmi"
model = "25053RT47C"
device = "onyx"
product = "onyx"
fingerprint = ""
name = "onyx"
marketname = "REDMI Turbo 4 Pro "
author = "Github@orangesroof"